#!/bin/bash
clear
fun_online() {
   ps aux | grep dropbear | grep -v grep | wc -l > /var/www/html/server/online
}
while true; do
    echo 'verificando...'
	fun_online > /dev/null 2>&1
	sleep 15s
done
