#!/bin/bash
#====================================================
#	@kiritosshxd
#====================================================
clear
[[ $(awk -F" " '{print $2}' /usr/lib/licence) != "@KIRITO_SSH" ]] && exit 0
fun_bar() {
    comando[0]="$1"
    comando[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${comando[0]} -y >/dev/null 2>&1
        ${comando[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "\033[1;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[1;31m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[1;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "\033[1;33m["
    done
    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}

fun_botOnOff() {
    [[ $(ps x | grep "bot_teste" | grep -v grep | wc -l) = '0' ]] && {
        clear
        rm botteste /etc/SSHPlus/bott/ > /dev/null 2>&1
        wget https://raw.githubusercontent.com/rodrigo12xd/SSHPLUS/master/Modulos/botteste /etc/SSHPlus/bott/ > /dev/null 2>&1
        clear
        echo -e "\E[44;1;37m             INSTALADOR BOT TESTE                \E[0m\n"
        echo -ne "\033[1;32mINFORME SEU TOKEN:\033[1;37m "
        read token
        echo -ne "\033[1;32mINFORME SEU USER: EX:@kiritosshxd\033[1;37m "
        read user
        clear
        echo -ne "\033[1;32mINFORME O NOME DO BOTÃO PARA GERAR O TESTE SSH:\033[1;37m "
        read botaossh
        clear
        echo -ne "\033[1;32mINFORME O NOME DO SEGUNDO BOTÃO (PERSONALIZADO):\033[1;37m "
        read botao2
        echo -ne "\033[1;32mINFORME O LINK PERSONALIZADO PARA O SEGUNDO BOTÃO:\033[1;37m "
        read linkb2
        clear
        echo -ne "\033[1;32mINFORME O NOME DO TERCEIRO BOTÃO (PERSONALIZADO):\033[1;37m "
        read botao3
        echo -ne "\033[1;32mINFORME O LINK PERSONALIZADO PARA O TERCEIRO BOTÃO:\033[1;37m "
        read linkb3
        echo ""
        clear
        echo -e "\033[1;32mINICIANDO BOT TESTE \033[0m\n"
        fun_bot1() {
        	[[ "$(grep -wc '16' /etc/issue.net)" != '0' ]] && {
        		wget -qO- https://raw.githubusercontent.com/rodrigo12xd/SSHPLUS/master/Install/ShellBot.sh > /etc/SSHPlus/bott/ShellBot.sh
        	}
            [[ ! -e "/etc/SSHPlus/bott/ShellBot.sh" ]] && {
				wget -qO- https://raw.githubusercontent.com/rodrigo12xd/SSHPLUS/master/Install/ShellBot.sh >/etc/SSHPlus/bott/ShellBot.sh
			}
            cd /etc/SSHPlus/bott
            sed -i 's/!user/$user/' /etc/SSHPlus/bott/botteste > /dev/null 2>&1
            sed -i 's/!botaossh/$botaossh/' /etc/SSHPlus/bott/botteste > /dev/null 2>&1
            sed -i 's/!botao2/$botao2/' /etc/SSHPlus/bott/botteste > /dev/null 2>&1
            sed -i 's/!linkb2/$linkb2/' /etc/SSHPlus/bott/botteste > /dev/null 2>&1
            sed -i 's/!botao2/$botao2/' /etc/SSHPlus/bott/botteste > /dev/null 2>&1
            sed -i 's/!linkb3/$linkb3/' /etc/SSHPlus/bott/botteste > /dev/null 2>&1
            screen -dmS bot_teste ./botteste $token >/dev/null 2>&1
            [[ $(grep -wc "bot_teste" /etc/autostart) = '0' ]] && {
                echo -e "ps x | grep 'bot_teste' | grep -v 'grep' || cd /etc/SSHPlus/bott && sudo screen -dmS bot_teste ./botteste $token && cd $HOME" >>/etc/autostart
            } || {
                sed -i '/bot_teste/d' /etc/autostart
                echo -e "ps x | grep 'bot_teste' | grep -v 'grep' || cd /etc/SSHPlus/bott && sudo screen -dmS bot_teste ./botteste $token && cd $HOME" >>/etc/autostart
            }
            [[ $(crontab -l | grep -c "verifbot") = '0' ]] && (
                crontab -l 2>/dev/null
                echo "@daily /bin/verifbot"
            ) | crontab -
            cd $HOME
        }
        fun_bar 'fun_bot1'
        [[ $(ps x | grep "bot_teste" | grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT TESTE ATIVADO !\033[0m" || echo -e "\n\033[1;31m ERRO! REANALISE SUAS INFORMACOES\033[0m"
        sleep 2
        menu
    } || {
        clear
        echo -e "\033[1;32mPARANDO BOT TESTE... \033[0m\n"
        fun_bot2() {
            screen -r -S "bot_teste" -X quit
            screen -wipe 1>/dev/null 2>/dev/null
            [[ $(grep -wc "bot_teste" /etc/autostart) != '0' ]] && {
                sed -i '/bot_teste/d' /etc/autostart
            }
            [[ $(crontab -l | grep -c "verifbot") != '0' ]] && crontab -l | grep -v 'verifbot' | crontab -
            sleep 1
        }
        fun_bar 'fun_bot2'
        echo -e "\n\033[1;32m \033[1;31mBOT TESTE PARADO! \033[0m"
        sleep 2
        menu
    }
}

fun_instbot() {
    echo -e "\E[44;1;37m             INSTALADOR BOT TESTE                \E[0m\n"
    echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENCAO \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
    echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mPELO SEU TELEGRAM ACESSE O SEGUINTE BOT\033[1;37m:\033[0m"
    echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCRIE O SEU BOT \033[1;31mOPCAO: \033[1;37m/newbot\033[0m"
    echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[1;32m"
    echo ""
    read -p "DESEJA CONTINUAR ? [s/n]: " -e -i s resposta
    [[ "$resposta" = 's' ]] && {
        fun_botOnOff
    } || {
        echo -e "\n\033[1;31mRetornando...\033[0m"
        sleep 2
        menu
    }
}
[[ -f "/etc/SSHPlus/bott/ShellBot.sh" ]] && fun_botOnOff || fun_instbot
#fim
