#!/bin/bash
clear
#--------@kiritosshxd-----------#
source ShellBot.sh
ShellBot.init --token "1999518553:AAEdKpGEHa3-zb5y_sgQxOyPet25LxkOkhg" --monitor --flush
ShellBot.username

# - Funcao menu
menu() {
    local msg
        msg="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n"
        msg+="<b>-------------SEJAM BEM VINDOS-------------</b>\n"
        msg+="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n\n"
        msg+="<b>VENDEDOR OFICIAL DO SOCKSLITE</b>\n"
	msg+="<b>VALOR:</b> 10 MENSAL\n"
	msg+="<b>PIX EMAIL: </b>rodrigorocha5733@gmail.com\n"
	msg+="<b>APERTE EM “COMPRAR ACESSO” E ENVIE SEU COMPROVANTE</b>\n\n"
        msg+="⚠️<b>APENAS CHAME SE REALMENTE FOR COMPRAR</b>⚠️\n"
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --reply_markup "$keyboard1" \
        --parse_mode html
        return 0
}

# - funcao criar ssh
criarteste() {
    [[ $(grep -wc ${callback_query_from_id} lista) != '0' ]] && {
      ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
        --text "VC JA CRIOU SSH HOJE !"
      return 0
    }
    usuario=$(echo lite$(( RANDOM% + 99999 )))
    senha=$((RANDOM% + 99999))
    limite='1'
    tempo='1'
    tuserdate=$(date '+%C%y/%m/%d' -d " +1 days")
    useradd -M -N -s /bin/false $usuario -e $tuserdate > /dev/null 2>&1
    (echo "$senha";echo "$senha") | passwd $usuario > /dev/null 2>&1
    echo "$senha" > /etc/SSHPlus/senha/$usuario
    echo "$usuario $limite" >> /root/usuarios.db
    echo "#!/bin/bash
pkill -f "$usuario"
userdel --force $usuario
grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
rm /etc/SSHPlus/senha/$usuario > /dev/null 2>&1
rm -rf /etc/SSHPlus/userteste/$usuario.sh" > /etc/SSHPlus/userteste/$usuario.sh
    chmod +x /etc/SSHPlus/userteste/$usuario.sh
    at -f /etc/SSHPlus/userteste/$usuario.sh now + $tempo hour > /dev/null 2>&1
    echo ${callback_query_from_id} >> lista
    # - ENVIA O SSH
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
    --text "$(echo -e "✅ <b>Criado com sucesso</b> ✅\n\nIP: $(cat /etc/IP)\nUSUARIO: <code>$usuario</code>\nSENHA: <code>$senha</code>\n\n⏳ Expira em: $tempo Hora")" \
    --parse_mode html
    return 0
}

criar_user2() {
  username=$(echo user$(( RANDOM% + 99999 )))
  password=$((RANDOM% + 99999))
  sshlimiter='1'
  dias='31'
  [[ "$(grep -wc $username /etc/passwd)" != '0' ]] && {
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
        --text "USUARIO GERADO JÁ FOI CADASTRADO, TENTE NOVAMENTE"
      return 0
  }
  final=$(date "+%Y-%m-%d" -d "+$dias days")
  gui=$(date "+%d/%m/%Y" -d "+$dias days")
  pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
  useradd -e $final -M -s /bin/false -p $pass $username >/dev/null 2>&1 &
  echo "$username" >/etc/SSHPlus/senha/$username
  echo "$username $sshlimiter" >>/root/usuarios.db
  ShellBot.sendMessage --chat_id ${message_from_id[$id]} \
    --text "<b>✅ CRIADO COM SUCESSO ✅</b>\n\nIP: $(cat /etc/IP)\nUSUARIO: <code>$usuario</code>\nSENHA: <code>$senha</code>\nLIMITE: <code>$sshlimiter<code>\n⏳ EXPIRA EM: 31 Dias" \
    --parse_mode html
    return 0
}

criaruser() {
    IP=$(cat /etc/IP)
    usuario=$(echo user$(( RANDOM% + 99999 )))
    senha=$((RANDOM% + 99999))
    limite='1'
    dias='31'
    final=$(date "+%Y-%m-%d" -d "+$dias days")
    gui=$(date "+%d/%m/%Y" -d "+$dias days")
    pass=$(perl -e 'print crypt($ARGV[0], "password")' $senha)
    useradd -e $final -M -s /bin/false -p $pass $usuario >/dev/null 2>&1 &
    echo "$usuario $limite" >>/root/usuarios.db
    echo "$senha" >/etc/SSHPlus/senha/$usuario

    echo "usuario $usuario $validade $senha criado"
    ShellBot.sendMessage --chat_id ${message_from_id[$id]} \
    --text "<b>✅ CRIADO COM SUCESSO ✅</b>\n\nIP: $(cat /etc/IP)\nUSUARIO: <code>$usuario</code>\nSENHA: <code>$senha</code>\nLIMITE: <code>$limite<code>\n⏳ EXPIRA EM: 31 Dias" \
    --parse_mode html
    return 0
}

#enviar app
enviarapp() {
    ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
        --text "♻️ ENVIANDO APLICATIVO, AGUARDE..."
    ShellBot.sendDocument --chat_id ${callback_query_message_chat_id} \
        --document "@/root/CONECT4G.apk" \
    return 0
}

#informacoes usuario
infouser () {
	ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
	--text "$(echo -e "Nome:  ${message_from_first_name[$(ShellBot.ListUpdates)]}\nUser: @${message_from_username[$(ShellBot.ListUpdates)]:-null}")\nID: ${message_from_id[$(ShellBot.ListUpdates)]} " \
	--parse_mode html
	return 0
}

unset botao1
botao1=''
ShellBot.InlineKeyboardButton --button 'botao1' --line 1 --text '♻️GERA TESTE♻️' --callback_data 'gerarssh'
ShellBot.InlineKeyboardButton --button 'botao1' --line 2 --text '♻️GERA SSH MENSAL♻️' --callback_data 'usercriar'
ShellBot.InlineKeyboardButton --button 'botao1' --line 3 --text '🔰BAIXAR APLICATIVO🔰' --callback_data 'appenviar'
ShellBot.InlineKeyboardButton --button 'botao1' --line 4 --text '💲COMPRAR ACESSO💲' --callback_data '3' --url 'https://t.me/kiritosshxd'
ShellBot.regHandleFunction --function criarteste --callback_data gerarssh
ShellBot.regHandleFunction --function enviarapp --callback_data appenviar
ShellBot.regHandleFunction --function criaruser --callback_data usercriar

unset keyboard1
keyboard1="$(ShellBot.InlineKeyboardMarkup -b 'botao1')"
while :; do
   [[ "$(date +%d)" != "$(cat RESET)" ]] && {
   	echo $(date +%d) > RESET
   	echo ' ' > lista
   }
  ShellBot.getUpdates --limit 100 --offset $(ShellBot.OffsetNext) --timeout 30
  for id in $(ShellBot.ListUpdates); do
    (
      ShellBot.watchHandle --callback_data ${callback_query_data[$id]}
      comando=(${message_text[$id]})
      [[ "${comando[0]}" = "/menu"  || "${comando[0]}" = "/start" ]] && menu
      [[ "${comando[0]}" = "/id"  ]] && infouser
    ) &
  done
done
